### ISSUE TITLE
Project is not written in Rust, the official language of the official GNU/Linux DE (Gnome)

### ISSUE THREAD

**Issue by tutitau** [nahuelwexd/Replay#75]
Steps to reproduce: click on project, github shows "Vala" what even is Vala?
Fix: rewrite in Rust

**Comment by nahuelwexd** [comment]
Uhm... I suggest you to look at some projects at the [GNOME GitLab instance](https://gitlab.gnome.org)...

https://gitlab.gnome.org/GNOME/vala
https://gitlab.gnome.org/GNOME/gnome-calculator
https://gitlab.gnome.org/GNOME/gnome-usage
https://gitlab.gnome.org/GNOME/gnome-games
https://gitlab.gnome.org/GNOME/seahorse
https://gitlab.gnome.org/GNOME/simple-scan
https://gitlab.gnome.org/GNOME/gnome-clocks
https://gitlab.gnome.org/GNOME/baobab
https://gitlab.gnome.org/GNOME/geary
https://gitlab.gnome.org/GNOME/gnome-boxes
https://gitlab.gnome.org/GNOME/gitg
https://gitlab.gnome.org/GNOME/connections
https://gitlab.gnome.org/GNOME/gnome-contacts
https://gitlab.gnome.org/GNOME/dconf-editor

(also, almost all games from the [GNOME Games Collection](https://wiki.gnome.org/Apps#Games) are written in Vala)

> what even is Vala?

A programming language built on top of all the GNOME technologies (GLib, GObject, GIO, GTK, etc) in order to provide high level programming techniques without the need of an additional runtime. Basically, you program in Vala, `valac` "compiles" that Vala code into C code using GLIb and other GNOME libraries, and then `gcc` (or whatever C compiler you use) compiles that into the actual binary. Has been a thing for the past... 15 years?

You can read more about it here -> https://wiki.gnome.org/Projects/Vala

> Rust, the official language of the official GNU/Linux DE (Gnome)

I dunno where you have read that Rust is the official language of GNOME but AFAIK, GNOME is not actively encouraging the use of any specific language, but rather allows you to program in the language you want... and I want to program in Vala, mainly 'cause I'm familiar with C# and Java (Rust syntax looks really alien to me).

PS: It's GNOME, not Gnome :) https://blogs.gnome.org/mcatanzaro/2020/02/01/lets-learn-spelling

**Comment by rhysperry111** [comment]
Sorry to barge in here, but I saw this in my emails and felt the need to comment.

@tutitau who the hell do you think you are? It's unbelievably rude and disrespectful to come to an open source project and try and demand that the maintainers do something. If you really believe so much that it needs to be written in rust, fork it and do it yourself

**Comment by Marki2019** [comment]
I wholeheartedly agree with this guy.

**Comment by tutitau** [comment]
meh... whatever. But no joke, Rust would be nice for "fearless concurrency" when dealing with thousands of subscriptions and there are some RSS libs (?needed for youtube?) out there that could be shared with another project (NewsFlash). And the overall ecosystem for scraping is probably more supported than C/Vala
At the end of the day, of course, whoever writes the code decides

@rhysperry111 just don't get offended at bug reports and it's all good

**Comment by Marki2019** [comment]
It's kind of hard to convert an entire program into another language, especially the one that's alien to someone (in this case Nahuel).

**Comment by nahuelwexd** [comment]
Well, since I'm hardly going to end up rewriting the project in Rust, I'm going to close the issue. The languages ​​that I use in my day to day are always with syntax similar to C/C#/Java/JavaScript, so getting involved right now into a Rust project would be uncomfortable and complicated.

Maybe I can choose Rust for another project in the future.

On the XML libraries, in the GObject ecosystem we have GXml, which looks quite good as an option to choose from, although we can always fall back to libxml
